### PR TITLE
Added new features

### PR DESCRIPTION
**Pull request by dominicankev**
Added Search with phrase - enters text into search field
Added Type utterance - types text into gui text fields
Added List Channels (by genre) - Lists channels by genre in new chnllist.json file (see example file)
Added List Genres - Lists genres available for channels (genres variable in apps.js file)
Added Change Channel (in/on ) - Optional utterance for one off channel change request
Added Put On (in/on ) - Optional utterance for one off channel change request
Added Force Channel (in/on ) - Optional utterance for one off channel change request

Tried to update support files to reflect new features

### CODE REVIEW

**Comment by jradwan** [comment]
Nice! I see the compares are finally working, thanks for "fixing" that.

I don't see the change to alexa-utterances you had mentioned earlier which was necessary to make the "in <room>" part of channel changing work. That was my concern about customizing a package that is a dependency of this project. Were you able to work around that, or is that still a requirement?

Thanks again for the contributions! I'll review and (once I figure out the alexa-utterances question above) complete the pull request.

**Comment by dominicankev** [comment]
Hey Jeremy,

Yeah, the change is still required for alexa-utterances but I just
submitted the change to the alexa-utterances repo so hopefully it gets
integrated.  I was completely using GitHub incorrectly.  Hence the issues.
 :' )

-Kevin

**Comment by dominicankev** [comment]
Looks like my utterance change was made to the alexa-utterances repo.  :' )

-Kevin

**Comment by dominicankev** [comment]
Jumped the gun...  Wasn't looking in the right repo...  Think Pull request
has been approved...  Just needs to be merged I think.

-Kevin

**Comment by jradwan** [comment]
Ok, once that's merged this PR should be good then, but I'll review/confirm. Thanks again!

**Comment by dominicankev** [comment]
No worries!  :' )

**Comment by jradwan** [comment]
A few comments:

- is the purpose of TIVOTYPEREQ_SLOT just to have pre-defined phrases for the Type and Search utterances? Do you have to explicitly list a phrase there in order to be able to search for it/type it?

- it looks like the '... browse' line was left out of docs/card.txt.

- the new chnllist.json file: is this a replacement for channels.json? or is it an additional file for the genre mapping? if so, it looks like you have to duplicate information in both files, right? I wonder if maybe these two files should be consolidated into one so that the name, channel number, pronunciation, and genre are all in one place?

- I wonder if the genres list (var genres) should be moved into a string in constants.json to make it more user-editable?

**Comment by dominicankev** [comment]
Responses below:

   -

   *is the purpose of TIVOTYPEREQ_SLOT just to have pre-defined phrases for
   the Type and Search utterances? Do you have to explicitly list a phrase
   there in order to be able to search for it/type it?*

I think I was trying to follow best practices for the custom slot type
where they recommended formatting the expected text in the slot.  I'm going
to try to find a predefined Amazon slot type for shows and movies and see
if I can get away without having to use the custom slot type which will
make it easier.



   -

   *it looks like the '... browse' line was left out of docs/card.txt.*

Might have been a mistake on my part.  Wasn't intentional I believe.



   -

   *the new chnllist.json file: is this a replacement for channels.json? or
   is it an additional file for the genre mapping? if so, it looks like you
   have to duplicate information in both files, right? I wonder if maybe these
   two files should be consolidated into one so that the name, channel number,
   pronunciation, and genre are all in one place?*

Right now it's an additional file since Alexa hears different variations
for me on certain channels (A&E and E! are a pain for Alexa to understand)
requiring the channels.json file.  If I had multiple entries for the same
channel in the chnllist.json it would mess up the output for the card and
Alexa would repeat the same channel multiple times.  I may need to do some
more testing to see if it's possible to consolidate the two but for now
it's two separate files.



   -

   *I wonder if the genres list (var genres) should be moved into a string
   in constants.json to make it more user-editable?*

Think you're right on that one Jeremy.  I was thinking of where best to put
it and at the time didn't think of the constants file.

I'll try to fix 2 and 4 and push sometime Sunday and will look further into
1 and 3.  Let me know if you have any additional questions.  Thanks!

**Comment by jradwan** [comment]
There are pre-defined slots for movies and TV:
- [AMAZON.Movies](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/slot-type-reference#movie)
- [AMAZON.MovieSeries](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/slot-type-reference#movieseries)
- [AMAZON.TVEpisode](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/slot-type-reference#tvepisode)
- [AMAZON.TVSeries](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/slot-type-reference#tvseries)

But I'm not sure if you can include multiple slot types in a single intent (i.e., Search). I mean, I know you can have multiple slots, but in this case it would an either/or scenario (only one of the four slots to be used). Hmm.

**Comment by dominicankev** [comment]
Yeah, I saw those.  Was thinking of trying to make those optional so we would see a bunch of different utterances for each scenario.  Not sure how it would process the request.  Can test though.

**Comment by dominicankev** [comment]
Hey Jeremy,

Made the changes and pushed them to the pull request.  Was able to get rid
of the custom slot request by using AMAZON.Movie and AMAZON.TVSeries.
Right now it looks like the app is just defaulting to using the
AMAZON.Movie slot so we may not end up needing both slots but they're in
there for now.  I added the genres variable as an object in the constants
file, and fixed the '...browse' line that was removed from docs/card.txt.
Now just need to wait for them to pull the trigger on my utterances pull
request.  Let me know if you find anything or have any other questions.

**Comment by jradwan** [comment]
Nice, thanks!

I think what I'll do is publish a new release ([v0.3.0](https://github.com/jradwan/alexa_tivo_control/tree/0.3.0-alpha)) just to get the current code "done" since it has the channel changing by name and new utterances. Then I'll go ahead and pull in this PR for the _next_ version (v0.4.0?) so I can start testing and such while we're waiting for the PR to alexa-utterances to be approved. 

This way I'll get to learn how PRs work too. 😉

**Comment by dominicankev** [comment]
Cool!  :' D

**Review by jradwan — APPROVED** [review]
Ok, here we go ... my first approved pull request!

**Comment by jradwan** [comment]
Any reason the "kids" genre is spelled with a Z in chnllist.json?

**Comment by dominicankev** [comment]
I think the Amazon.Genre slot type has kidz as the entry possibly.  Every
time the echo would hear kids it would interpret it as kidz so I had to
change my entries to kidz for it to properly list the channels.

**Comment by jradwan** [comment]
Ok, interesting. I'll leave it like that then!

**Pull request merged**
